version: '3.4'

services:
  blazorapp:
    image: blazorapp
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5071:443"   
    depends_on:
      - grpc
  grpc:
    image: grpc
    build:
      context: .
      dockerfile: Dockerfile.grpc
    ports:
      - "7017:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"